/* Generated by Yosys 0.43 (git sha1 ead4718e5, clang++ 15.0.0 -fPIC -Os) */

module circuit(x, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire a;
  wire b;
  wire c;
  wire d;
  input [3:0] x;
  wire [3:0] x;
  output [1:0] y;
  wire [1:0] y;
  INV _11_ (
    .A(x[1]),
    .Y(_08_)
  );
  INV _12_ (
    .A(x[0]),
    .Y(_09_)
  );
  AND2 _13_ (
    .A(x[1]),
    .B(x[3]),
    .Y(_10_)
  );
  AND2 _14_ (
    .A(x[1]),
    .B(_09_),
    .Y(_00_)
  );
  NAND2 _15_ (
    .A(x[3]),
    .B(x[2]),
    .Y(_01_)
  );
  NAND2 _16_ (
    .A(_08_),
    .B(x[2]),
    .Y(_02_)
  );
  NAND2 _17_ (
    .A(_09_),
    .B(_02_),
    .Y(_03_)
  );
  AND2 _18_ (
    .A(_01_),
    .B(_03_),
    .Y(_04_)
  );
  XOR2 _19_ (
    .A(_10_),
    .B(_04_),
    .Y(y[0])
  );
  NAND2 _20_ (
    .A(_08_),
    .B(x[0]),
    .Y(_05_)
  );
  OR2 _21_ (
    .A(x[3]),
    .B(x[2]),
    .Y(_06_)
  );
  NAND2 _22_ (
    .A(_00_),
    .B(_06_),
    .Y(_07_)
  );
  NAND2 _23_ (
    .A(_05_),
    .B(_07_),
    .Y(y[1])
  );
  assign a = x[0];
  assign b = x[1];
  assign c = x[2];
  assign d = x[3];
endmodule
