/* Generated by Yosys 0.43 (git sha1 ead4718e5, clang++ 15.0.0 -fPIC -Os) */

module circuit(x, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire a;
  wire b;
  wire c;
  wire d;
  input [3:0] x;
  wire [3:0] x;
  output [1:0] y;
  wire [1:0] y;
  assign _06_ = ~(x[1] & x[3]);
  assign _07_ = x[2] | ~(x[0]);
  assign _08_ = x[3] | ~(x[2]);
  assign _00_ = ~(_07_ & _08_);
  assign _01_ = x[1] & ~(x[0]);
  assign _02_ = _00_ & ~(_01_);
  assign y[0] = ~(_06_ ^ _02_);
  assign _03_ = x[1] | ~(x[0]);
  assign _04_ = x[3] | x[2];
  assign _05_ = ~(_01_ & _04_);
  assign y[1] = ~(_03_ & _05_);
  assign a = x[0];
  assign b = x[1];
  assign c = x[2];
  assign d = x[3];
endmodule
