/* Generated by Yosys 0.43 (git sha1 ead4718e5, clang++ 15.0.0 -fPIC -Os) */

module circuit(x, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire a;
  wire b;
  wire c;
  wire d;
  input [3:0] x;
  wire [3:0] x;
  output [1:0] y;
  wire [1:0] y;
  INV _07_ (
    .A(x[1]),
    .Y(_04_)
  );
  INV _08_ (
    .A(x[0]),
    .Y(_05_)
  );
  INV _09_ (
    .A(x[3]),
    .Y(_06_)
  );
  OAI211 _10_ (
    .A1(_05_),
    .A2(x[2]),
    .B1(x[3]),
    .C1(x[1]),
    .Y(_00_)
  );
  MUX2 _11_ (
    .A(_05_),
    .B(x[3]),
    .S(x[2]),
    .Y(_01_)
  );
  AOI21 _12_ (
    .A1(x[0]),
    .A2(_06_),
    .B1(_04_),
    .Y(_02_)
  );
  OAI21 _13_ (
    .A1(_01_),
    .A2(_02_),
    .B1(_00_),
    .Y(y[0])
  );
  OAI211 _14_ (
    .A1(x[3]),
    .A2(x[2]),
    .B1(x[1]),
    .C1(_05_),
    .Y(_03_)
  );
  OAI21 _15_ (
    .A1(x[1]),
    .A2(_05_),
    .B1(_03_),
    .Y(y[1])
  );
  assign a = x[0];
  assign b = x[1];
  assign c = x[2];
  assign d = x[3];
endmodule
